### PR TITLE
Safe Harbor Agreement Implementation Standard

### PR DESCRIPTION
**Pull request by Robert-MacWha**
## EDIT: 2024-06-23
Marking this PR as functionally complete.  Changes to form may be performed, but avoid making functional changes barring catastrophe.

## Original Message
Following up with Discussion https://github.com/security-alliance/safe-harbor/discussions/4, I created this document as a V1 of the _Safe Harbor Agreement Implementation Standard_.  It outlines a standardization for the contents of `AgreementDetails`, ensuring consistency and compliance across all agreements. Standardization of these contents will help Whitehats understand the contents of the Agreement more easily in potentially time-sensitive environments, and will help software parse and display multiple agreements in a standardized manner. 

It outlines specific standards in JSON format for the `scope`, `contactDetails` and `bountyTerms` fields of the `AgreementDetails` struct, providing structured information regarding `static assets`, `implicit assets`, `primary` and `secondary contacts`, `identity requirements`, `diligence requirements`, `bounty percentage`, `cap`, and `retainability`; and sections for `additional information` where necessary.

### CODE REVIEW

**Comment by rholterhus** [comment]
Amazing, thanks for putting this together. The structure looks good to me, and one interesting thing I hadn't considered before is your `implicitAssets` idea (in the `scope` field) where you can specify a deployer address instead of a fixed set of addresses. This seems like a reasonable choice for protocols that use a factory contract to deploy things.

Before merging the PR I'm going to do two things:

1. Double-check whether the on-chain component or the IPFS component should take precedence legally (I forget the answer). Depending on the answer it might require a quick change here:
    
    > In the event of any conflict or inconsistency between information in the `AgreementDetails` and the text of the Agreement, the text of the Agreement will govern  


2. Will check if we should wait to officially merge this once we have a few more incoming changes ready (working on some reorganizing and other small tweaks)

Thanks again and will circle back here

**Comment by Robert-MacWha** [comment]
> 1. Double-check whether the on-chain component or the IPFS component should take precedence legally (I forget the answer). Depending on the answer it might require a quick change here:

Should have linked to the Agreement — I got this from EXHIBIT F (Adoption Form) where it states “In the event of any conflict or inconsistency between the summary and the text of the Agreement, the text of the Agreement will govern.”  Sounded like the text of the Agreement is the source of truth, so I included similar language.

Probably good idea to double-check.

**Comment by Robert-MacWha** [comment]
I was making the website form, and it occurred to me that `direct` and `child` are probably better terms that `static` and `implicity`. 

Updated the PR - if you have any objections let me know.

**Comment by Robert-MacWha** [comment]
RE: The conversion I had with Gabe.

Updated the smart contracts to have upgradable agreements & to encode the implementation standard in code.  In short, adopting the agreement now requires deploying a smart contract that will record adoption details from a pre-approved contract deployed.

**Adoption changes**
Adoption requires calling the `adoptSafeHarbor` method on the `AgreementDetailDeployerV1` contract while providing the adoption-specific `AgreementDetailsV1`.  Calling `adoptSafeHarbor` method will:
1. Deploy a `AgreementV1` contract that records the `AgreementDetailsV1` on-chain 
2. Call `recordAdoption` on the main registry contract, which will in turn record the adoption in the registry's mapping and emit an `SafeHarborAdoption` event.

**Setup Changes** 
Initial setup of the registry is now more involved.  In addition to deploying the main registry contract (_which requires an admin account_) a `AgreementDetailDeployer` must also be deployed and approved using the registry contract's `approveDeployer` method.

**AdoptionDetails Changes**
The structure of the `AgreementDetails` struct has again been changed to increase specificity.  The new structure mirrors that within the legal contracts.

```solidity
struct AgreementDetailsV1 {
    // The name of the protocol adopting the agreement.
    string protocolName;
    // The assets in scope of the agreement.
    Asset[] scope;
    // The contact details (required for pre-notifying).
    Contact[] contactDetails;
    // The bounty terms.
    BountyTerms bountyTerms;
    // Indication whether the agreement should be automatically upgraded to future versions approved by SEAL.
    bool automaticallyUpgrade;
    // Address where recovered funds should be sent.
    address assetRecoveryAddress;
    // IPFS hash of the actual agreement document, which confirms all terms.
    string agreementURI;
}

struct Asset {
    // The address of the asset.
    address assetAddress;
    // The chain IDs on which the asset is deployed.
    uint[] chainIDs;
    // Whether smart contracts deployed by this address are in scope.
    bool includeChildContracts;
    // Whether smart contracts deployed by this address after the agreement is adopted are in scope.
    bool includeNewChildContracts;
}

struct Contact {
    // The name of the contact.
    string name;
    // The email of the contact.
    string email;
    // The phone number of the contact.
    string phone;
}

enum IdentityRequirement {
    Anonymous,
    Pseudonymous,
    Named
}

struct BountyTerms {
    // Percentage of the recovered funds a Whitehat receives as their bounty (0-100).
    uint bountyPercentage;
    // The maximum bounty in USD.
    uint bountyCapUSD;
    // Indicates if the Whitehat can retain their bounty.
    bool retainable;
    // Identity requirements for Whitehats eligible under the agreement.
    IdentityRequirement identityRequirement;
    // Description of what KYC, sanctions, diligence, or other verification will be performed on Whitehats to determine their eligibility to receive the bounty.
    string diligenceRequirements;
}
```

**Comment by Robert-MacWha** [comment]
Smart contracts are functionally complete 🧇!

Updates on Agreement Structure:
- We created a new `Chain` struct that contains the `assetRecoveryAddress`, the list of `Account`s, and a chainID.  This was done so that different chains could define different recovery addresses in case the protocol wasn't using a deterministic deployment method.
- We removed the `chainIDs` list from the `Account` struct since the chain is defined by the parent `Chain` struct.
- The `Account` struct was modified to have a `ChildContractScope` enum instead of the two `includeChildContracts` and `includeNewChildContracts` bools.  This was done so that the child scope could be more explicit (`None`, `ExistingOnly`, `All`).
- Added a new `signature` field to the `Account` struct (see below.)

New Feature - Signatures:
- Signatures are optional.  For contracts that don't implement ERC-1271 or for accounts that don't want to bother with signatures, the field will be left blank.
- In the case that a signature is provided, whitehats will know that the person holding the account's private key has signed the agreement details.  It acts as a decentralized method of verification.
- In the case that a signature is not provided, nothing changes.

Full Agreement Struct:
```solidity
/// @notice Struct that contains the details of the agreement.
struct AgreementDetailsV1 {
    // The name of the protocol adopting the agreement.
    string protocolName;
    // The scope and recovery address by chain.
    Chain[] chains;
    // The contact details (required for pre-notifying).
    Contact[] contactDetails;
    // The terms of the agreement.
    BountyTerms bountyTerms;
    // Indication whether the agreement should be automatically upgraded to future versions approved by SEAL.
    bool automaticallyUpgrade;
    // IPFS hash of the actual agreement document, which confirms all terms.
    string agreementURI;
}

/// @notice Struct that contains the details of an agreement by chain.
struct Chain {
    // The accounts in scope for the agreement.
    Account[] accounts;
    // The address to which recovered assets will be sent.
    address assetRecoveryAddress;
    // The chain ID.
    uint chainID;
}

/// @notice Enum that defines the inclusion of child contracts in an agreement.
enum ChildContractScope {
    // No child contracts are included.
    None,
    // Only existing child contracts are included.
    ExistingOnly,
    // All child contracts, both existing and new, are included.
    All
}

/// @notice Struct that contains the details of an account in an agreement.
struct Account {
    // The address of the account (EOA or smart contract).
    address accountAddress;
    // The scope of child contracts included in the agreement.
    ChildContractScope childContractScope;
    // The signature of the account. Optionally used to verify that this account has accepted this agreement.
    bytes signature;
}

/// @notice Struct that contains the contact details of the agreement.
struct Contact {
    // The name of the contact.
    string name;
    // The role of the contact.
    string role;
    // The contact details (IE email, phone, telegram).
    string contact;
}

/// @notice Enum that defines the identity requirements for a Whitehat to be eligible under the agreement.
enum IdentityRequirement {
    // The Whitehat has no moniker and no identifying information about the Whitehat has been verified.
    Anonymous,
    // The Whitehat uses a moniker but there has been limited or no verification of the legal name(s) of person(s) or entity behind the moniker.
    Pseudonymous,
    // The Whitehat is using a legal individual or entity name and that identity has been verified.
    Named
}

// @notice Struct that contains the terms of the bounty for the agreement.
struct BountyTerms {
    // Percentage of the recovered funds a Whitehat receives as their bounty (0-100).
    uint bountyPercentage;
    // The maximum bounty in USD.
    uint bountyCapUSD;
    // Indicates if the Whitehat can retain their bounty.
    bool retainable;
    // Identity requirements for Whitehats eligible under the agreement.
    IdentityRequirement identityRequirement;
    // Description of what KYC, sanctions, diligence, or other verification will be performed on Whitehats to determine their eligibility to receive the bounty.
    string diligenceRequirements;
}
```

**Pull request merged**
